<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\WaterTariff;

class UpdatedWaterTariffSeeder extends Seeder
{
    /**
     * Run the database seeds based on PDAM Purbalingga official tariff table.
     */
    public function run(): void
    {
        // Clear existing data
        WaterTariff::truncate();
        
        $legalBasisWaterTariff = 'Peraturan Bupati Purbalingga No.62 Tahun 2011 tanggal 14 Juni 2011 Tentang penyesuaian Tarif Dasar Air pada PDAM Kabupaten Purbalingga';
        
        $tariffs = [
            // SOSIAL - SOSIAL UMUM (HU)
            [
                'customer_type' => 'Sosial',
                'sub_category' => 'SOSIAL UMUM (HU)',
                'description' => 'Sosial Umum (HU) - 0-10 m³',
                'legal_basis' => $legalBasisWaterTariff,
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 780,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 1,
                'show_in_navbar' => true,
                'navbar_order' => 1,
                'navbar_label' => 'Sosial Umum (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Sosial',
                'sub_category' => 'SOSIAL UMUM (HU)',
                'description' => 'Sosial Umum (HU) - 11-20 m³',
                'legal_basis' => $legalBasisWaterTariff,
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 780,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 2,
                'show_in_navbar' => true,
                'navbar_order' => 2,
                'navbar_label' => 'Sosial Umum (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Sosial',
                'description' => 'Sosial Umum (HU) - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 780,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 3,
                'show_in_navbar' => true,
                'navbar_order' => 3,
                'navbar_label' => 'Sosial Umum (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Sosial',
                'description' => 'Sosial Umum (HU) - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 780,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 4,
                'show_in_navbar' => true,
                'navbar_order' => 4,
                'navbar_label' => 'Sosial Umum (>30m³)',
                'is_navbar_featured' => false,
            ],

            // SOSIAL - SOSIAL KHUSUS
            [
                'customer_type' => 'Sosial',
                'description' => 'Sosial Khusus - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 850,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 5,
                'show_in_navbar' => true,
                'navbar_order' => 5,
                'navbar_label' => 'Sosial Khusus (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Sosial',
                'description' => 'Sosial Khusus - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1140,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 6,
                'show_in_navbar' => true,
                'navbar_order' => 6,
                'navbar_label' => 'Sosial Khusus (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Sosial',
                'description' => 'Sosial Khusus - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 1550,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 7,
                'show_in_navbar' => true,
                'navbar_order' => 7,
                'navbar_label' => 'Sosial Khusus (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Sosial',
                'description' => 'Sosial Khusus - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 2090,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 8,
                'show_in_navbar' => true,
                'navbar_order' => 8,
                'navbar_label' => 'Sosial Khusus (>30m³)',
                'is_navbar_featured' => false,
            ],

            // NON NIAGA - RUMAH TANGGA KHUSUS
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga Khusus - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 990,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 9,
                'show_in_navbar' => true,
                'navbar_order' => 9,
                'navbar_label' => 'RT Khusus (0-10m³)',
                'is_navbar_featured' => true,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga Khusus - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1300,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 10,
                'show_in_navbar' => true,
                'navbar_order' => 10,
                'navbar_label' => 'RT Khusus (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga Khusus - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 1800,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 11,
                'show_in_navbar' => true,
                'navbar_order' => 11,
                'navbar_label' => 'RT Khusus (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga Khusus - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 2400,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 12,
                'show_in_navbar' => true,
                'navbar_order' => 12,
                'navbar_label' => 'RT Khusus (>30m³)',
                'is_navbar_featured' => false,
            ],

            // NON NIAGA - RUMAH TANGGA A
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga A - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 1100,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 13,
                'show_in_navbar' => true,
                'navbar_order' => 13,
                'navbar_label' => 'RT A (0-10m³)',
                'is_navbar_featured' => true,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga A - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1480,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 14,
                'show_in_navbar' => true,
                'navbar_order' => 14,
                'navbar_label' => 'RT A (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga A - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 2000,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 15,
                'show_in_navbar' => true,
                'navbar_order' => 15,
                'navbar_label' => 'RT A (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga A - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 2700,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 16,
                'show_in_navbar' => true,
                'navbar_order' => 16,
                'navbar_label' => 'RT A (>30m³)',
                'is_navbar_featured' => false,
            ],

            // Continue with other categories...
            // NON NIAGA - RUMAH TANGGA B
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga B - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 1190,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 17,
                'show_in_navbar' => true,
                'navbar_order' => 17,
                'navbar_label' => 'RT B (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga B - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1600,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 18,
                'show_in_navbar' => true,
                'navbar_order' => 18,
                'navbar_label' => 'RT B (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga B - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 2160,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 19,
                'show_in_navbar' => true,
                'navbar_order' => 19,
                'navbar_label' => 'RT B (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga B - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 2930,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 20,
                'show_in_navbar' => true,
                'navbar_order' => 20,
                'navbar_label' => 'RT B (>30m³)',
                'is_navbar_featured' => false,
            ],

            // NON NIAGA - RUMAH TANGGA C
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga C - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 1280,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 21,
                'show_in_navbar' => true,
                'navbar_order' => 21,
                'navbar_label' => 'RT C (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga C - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1730,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 22,
                'show_in_navbar' => true,
                'navbar_order' => 22,
                'navbar_label' => 'RT C (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga C - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 2340,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 23,
                'show_in_navbar' => true,
                'navbar_order' => 23,
                'navbar_label' => 'RT C (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Rumah Tangga',
                'description' => 'Rumah Tangga C - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 3160,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 24,
                'show_in_navbar' => true,
                'navbar_order' => 24,
                'navbar_label' => 'RT C (>30m³)',
                'is_navbar_featured' => false,
            ],

            // INSTANSI PEMERINTAH
            [
                'customer_type' => 'Instansi',
                'description' => 'Instansi Pemerintah - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 1380,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 25,
                'show_in_navbar' => true,
                'navbar_order' => 25,
                'navbar_label' => 'Instansi (0-10m³)',
                'is_navbar_featured' => true,
            ],
            [
                'customer_type' => 'Instansi',
                'description' => 'Instansi Pemerintah - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1850,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 26,
                'show_in_navbar' => true,
                'navbar_order' => 26,
                'navbar_label' => 'Instansi (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Instansi',
                'description' => 'Instansi Pemerintah - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 2500,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 27,
                'show_in_navbar' => true,
                'navbar_order' => 27,
                'navbar_label' => 'Instansi (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Instansi',
                'description' => 'Instansi Pemerintah - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 3380,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 28,
                'show_in_navbar' => true,
                'navbar_order' => 28,
                'navbar_label' => 'Instansi (>30m³)',
                'is_navbar_featured' => false,
            ],

            // TNI/POLRI
            [
                'customer_type' => 'TNI/Polri',
                'description' => 'TNI/POLRI - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 1380,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 29,
                'show_in_navbar' => true,
                'navbar_order' => 29,
                'navbar_label' => 'TNI/Polri (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'TNI/Polri',
                'description' => 'TNI/POLRI - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 1850,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 30,
                'show_in_navbar' => true,
                'navbar_order' => 30,
                'navbar_label' => 'TNI/Polri (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'TNI/Polri',
                'description' => 'TNI/POLRI - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 2500,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 31,
                'show_in_navbar' => true,
                'navbar_order' => 31,
                'navbar_label' => 'TNI/Polri (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'TNI/Polri',
                'description' => 'TNI/POLRI - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 3380,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 32,
                'show_in_navbar' => true,
                'navbar_order' => 32,
                'navbar_label' => 'TNI/Polri (>30m³)',
                'is_navbar_featured' => false,
            ],

            // NIAGA KECIL
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Kecil - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 1840,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 33,
                'show_in_navbar' => true,
                'navbar_order' => 33,
                'navbar_label' => 'Niaga Kecil (0-10m³)',
                'is_navbar_featured' => true,
            ],
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Kecil - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 2480,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 34,
                'show_in_navbar' => true,
                'navbar_order' => 34,
                'navbar_label' => 'Niaga Kecil (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Kecil - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 3350,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 35,
                'show_in_navbar' => true,
                'navbar_order' => 35,
                'navbar_label' => 'Niaga Kecil (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Kecil - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 4530,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 36,
                'show_in_navbar' => true,
                'navbar_order' => 36,
                'navbar_label' => 'Niaga Kecil (>30m³)',
                'is_navbar_featured' => false,
            ],

            // NIAGA BESAR
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Besar - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 2060,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 37,
                'show_in_navbar' => true,
                'navbar_order' => 37,
                'navbar_label' => 'Niaga Besar (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Besar - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 2920,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 38,
                'show_in_navbar' => true,
                'navbar_order' => 38,
                'navbar_label' => 'Niaga Besar (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Besar - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 3950,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 39,
                'show_in_navbar' => true,
                'navbar_order' => 39,
                'navbar_label' => 'Niaga Besar (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Niaga',
                'description' => 'Niaga Besar - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 5160,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 40,
                'show_in_navbar' => true,
                'navbar_order' => 40,
                'navbar_label' => 'Niaga Besar (>30m³)',
                'is_navbar_featured' => false,
            ],

            // INDUSTRI KECIL
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Kecil - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 2060,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 41,
                'show_in_navbar' => true,
                'navbar_order' => 41,
                'navbar_label' => 'Industri Kecil (0-10m³)',
                'is_navbar_featured' => true,
            ],
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Kecil - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 2920,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 42,
                'show_in_navbar' => true,
                'navbar_order' => 42,
                'navbar_label' => 'Industri Kecil (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Kecil - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 3950,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 43,
                'show_in_navbar' => true,
                'navbar_order' => 43,
                'navbar_label' => 'Industri Kecil (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Kecil - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 5160,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 44,
                'show_in_navbar' => true,
                'navbar_order' => 44,
                'navbar_label' => 'Industri Kecil (>30m³)',
                'is_navbar_featured' => false,
            ],

            // INDUSTRI BESAR
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Besar - 0-10 m³',
                'min_usage' => 0,
                'max_usage' => 10,
                'rate_per_m3' => 2290,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 45,
                'show_in_navbar' => true,
                'navbar_order' => 45,
                'navbar_label' => 'Industri Besar (0-10m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Besar - 11-20 m³',
                'min_usage' => 11,
                'max_usage' => 20,
                'rate_per_m3' => 3100,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 46,
                'show_in_navbar' => true,
                'navbar_order' => 46,
                'navbar_label' => 'Industri Besar (11-20m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Besar - 21-30 m³',
                'min_usage' => 21,
                'max_usage' => 30,
                'rate_per_m3' => 4190,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 47,
                'show_in_navbar' => true,
                'navbar_order' => 47,
                'navbar_label' => 'Industri Besar (21-30m³)',
                'is_navbar_featured' => false,
            ],
            [
                'customer_type' => 'Industri',
                'description' => 'Industri Besar - >30 m³',
                'min_usage' => 31,
                'max_usage' => null,
                'rate_per_m3' => 5650,
                'admin_fee' => 0,
                'maintenance_fee' => 0,
                'effective_date' => '2025-01-01',
                'is_active' => true,
                'sort_order' => 48,
                'show_in_navbar' => true,
                'navbar_order' => 48,
                'navbar_label' => 'Industri Besar (>30m³)',
                'is_navbar_featured' => false,
            ],
        ];

        // Insert data dengan menambahkan legal_basis
        foreach ($tariffs as $tariff) {
            if (!isset($tariff['legal_basis'])) {
                $tariff['legal_basis'] = $legalBasisWaterTariff;
            }
            if (!isset($tariff['sub_category'])) {
                // Extract sub_category from description
                if (strpos($tariff['description'], 'Sosial Umum') !== false) $tariff['sub_category'] = 'SOSIAL UMUM (HU)';
                elseif (strpos($tariff['description'], 'Sosial Khusus') !== false) $tariff['sub_category'] = 'SOSIAL KHUSUS';
                elseif (strpos($tariff['description'], 'Rumah Tangga Khusus') !== false) $tariff['sub_category'] = 'RUMAH TANGGA KHUSUS';
                elseif (strpos($tariff['description'], 'Rumah Tangga A') !== false) $tariff['sub_category'] = 'RUMAH TANGGA A';
                elseif (strpos($tariff['description'], 'Rumah Tangga B') !== false) $tariff['sub_category'] = 'RUMAH TANGGA B';
                elseif (strpos($tariff['description'], 'Rumah Tangga C') !== false) $tariff['sub_category'] = 'RUMAH TANGGA C';
                elseif (strpos($tariff['description'], 'Instansi Pemerintah') !== false) $tariff['sub_category'] = 'INSTANSI PEMERINTAH';
                elseif (strpos($tariff['description'], 'TNI/POLRI') !== false) $tariff['sub_category'] = 'TNI/POLRI';
                elseif (strpos($tariff['description'], 'Niaga Kecil') !== false) $tariff['sub_category'] = 'NIAGA KECIL';
                elseif (strpos($tariff['description'], 'Niaga Besar') !== false) $tariff['sub_category'] = 'NIAGA BESAR';
                elseif (strpos($tariff['description'], 'Industri Kecil') !== false) $tariff['sub_category'] = 'INDUSTRI KECIL';
                elseif (strpos($tariff['description'], 'Industri Besar') !== false) $tariff['sub_category'] = 'INDUSTRI BESAR';
                else $tariff['sub_category'] = $tariff['customer_type'];
            }
            WaterTariff::create($tariff);
        }
    }
}
